name: cross_connectivity
version: 3.3.1
homepage: https://github.com/marchdev-tk/cross_connectivity
description: A Flutter plugin for handling Connectivity and REAL Connection state in the mobile, web and desktop platforms. Supports iOS, Android, Web, Windows, Linux and macOS.
publish_to: 'none'
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.7.0
  http: ^0.13.1
  rxdart: ^0.26.0
  connectivity_plus:
     git:
       url: https://github.com/emirbashiri/connectivity_plus
       ref: main

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
